import {
  Home,
  ChevronRight,
  ChevronLeft,
  Users,
  FileText,
  BarChart2,
  CalendarDays,
  Clock,
  CalendarCheck2,
  Settings,
  LogOut,
  PlusCircle,
  User,
  LayoutDashboard,
  List,
  HelpCircle,
  Users2,
} from 'lucide-react';

export const Icons = {
  home: Home,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  users: Users,
  invoices: FileText,
  analytics: BarChart2,
  workshops: CalendarDays,
  timeSlots: Clock,
  bookings: CalendarCheck2,
  settings: Settings,
  logout: LogOut,
  create: PlusCircle,
  profile: User,
  dashboard: LayoutDashboard,
  categories: List,
  faq: HelpCircle,
  team: Users2,
};